volumes:
  medical-vol:

services:
  pgsql:
    image: postgres:12.11
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: usr
      POSTGRES_DB: medical
    volumes:
      - medical-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - pgsql
    ports:
      - 80:5000
    volumes:
      - ./app:/usr/src/app
